name: CI

on:
  push:
    branches: [develop, main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check shell scripts
        run: shellcheck scripts/*.sh

      - name: Check YAML is valid
        run: python3 -c "import yaml,sys; yaml.safe_load(open('docker-compose.yml'))"


  build:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/manas-rajadnya/shiptrack:${{ github.sha }}

  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Get AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::175342148773:role/github-actions-shiptrack
          aws-region: eu-north-1

      - name: Prove we have AWS access with no stored key
        run: |
          aws sts get-caller-identity
          aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId,State.Name]' --output table


  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::175342148773:role/github-actions-shiptrack
          aws-region: eu-north-1

      - name: Deploy to production
        run: |
          echo "Deploying image ghcr.io/manas-rajadnya/shiptrack:${{ github.sha }}"
          aws sts get-caller-identity



